project:
  type: website
  output-dir: docs
  execute-dir: project

  render:
    - index.qmd
    - "Notebooks/*.ipynb"
    - "Slides/*.qmd"

website:
  title: "HS 821: Topics in Time Series Econometrics"

  # This must match your GitHub username and repository name
  site-url: "https://sunilpaul29.github.io/HS821/"

  description: "Lecture notes, R examples, and supporting resources"

  page-navigation: true

  navbar:
    background: primary

    left:
      - href: index.qmd
        text: Home

    right:
      - icon: mortarboard
        text: Moodle
        href: "https://moodle.iitgoa.ac.in/course/view.php?id=1275"

  sidebar:
    style: docked
    search: true

    contents:
      - href: index.qmd
        text: Course home

      - section: "Preliminaries"
        contents:
          - href: Notebooks/01-Review-R.ipynb
            text: Review of R

          - href: Notebooks/02-Review-stats.ipynb
            text: Statistics and probability I

          - href: Notebooks/03-Review-stats1.ipynb
            text: Statistics and probability II

          - href: Notebooks/04-Review-stats2.ipynb
            text: Statistics and probability III

      - section: "Univariate timeseris models"
        contents:
          - href: Notebooks/05-Univariate-Time-Series-modelsI.ipynb
            text: Univariate-Time-Series-models I

      - section: "Lecture slides"
        contents:
          - href: Slides/00-course-introduction.qmd
            text: Course introduction

          - href: Slides/01-Review-stats-slides.qmd
            text: Review of Stats and Prob I

          - href: Slides/03-Review-stats1.qmd
            text: Review of Stats and Prob II

          - href: Slides/04-Review-stats2.qmd
            text: Review of Stats and Prob III

          - href: Slides/05-Univariate-Time-Series-modelsI.qmd
            text: Univariate-Time-Series-models I



  page-footer:
    left: "HS 821: Topics in Time Series Econometrics"
    right: "Moodle remains the official course platform."

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    code-summary: "Show R code"
    code-tools: true
    code-overflow: wrap
    link-external-newwindow: true

execute:
  enabled: false